apiVersion: apps/v1
kind: Deployment
metadata:
  name: myJavaApp
  labels:
    app: myJavaApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myJavaApp
  template:
    metadata:
      labels:
        app: myJavaApp
    spec:
      containers:
      - name: myJavaApp
        image: 498678202908.dkr.ecr.us-east-1.amazonaws.com/latesh:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myJavaApp
spec:
  selector:
    app: myJavaApp
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080